llm:
  model: "gpt-4o"
  max_tokens: 4000
  temperature: 0.1
  max_context_tokens: 128000

file_processing:
  supported_extensions:
    - .py
    - .js
    - .ts
    - .jsx
    - .tsx
    - .java
    - .cpp
    - .c
    - .h
    - .hpp
    - .cs
    - .swift
    - .go
    - .rs
    - .php
    - .rb
    - .scala
    - .kt
    - .dart
    - .r
    - .m
    - .mm
    - .sh
    - .sql
  
  exclude_patterns:
    - "*/node_modules/*"
    - "*/venv/*" 
    - "*/.git/*"
    - "*/build/*"
    - "*/dist/*"
    - "*/__pycache__/*"
    - "*.min.js"
    - "*.bundle.js"

output:
  markdown_template: |
    # Code Analysis: {project_name}
    
    ## Overview
    - **Languages Detected**: {languages}
    - **Total Files**: {total_files}
    - **Analysis Date**: {date}
    
    ## Project Summary
    {project_summary}
    
    ## File Analysis
    {file_analysis}
    
    ## Dependencies
    {dependencies}