# Docker Compose for Multi Container Deployment
# Separate containers for API and Frontend

version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      # API Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o}

      # Application Settings
      - DEBUG=${DEBUG:-false}
      - API_TITLE=${API_TITLE:-Code Summarizer API}
      - API_VERSION=${API_VERSION:-1.0.0}

      # Docker specific
      - CONTAINER_MODE=multi
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}

    env_file:
      - .env

    volumes:
      # Optional: Mount for development
      - type: bind
        source: ./logs/api
        target: /var/log/app
        bind:
          create_host_path: true

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:$${API_PORT:-8000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - code-summarizer-net

  # Frontend (Nginx)
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        - API_URL=http://api:${API_PORT:-8000}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - API_BASE_URL=http://api:${API_PORT:-8000}
      - CONTAINER_MODE=multi
      - FRONTEND_PORT=${FRONTEND_PORT:-80}

    depends_on:
      api:
        condition: service_healthy

    volumes:
      # Optional: Mount for development
      - type: bind
        source: ./logs/frontend
        target: /var/log/nginx
        bind:
          create_host_path: true

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    networks:
      - code-summarizer-net

networks:
  code-summarizer-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16