# Docker Compose for Single Container Deployment
# Runs both API and Frontend in one container

version: '3.8'

services:
  code-summarizer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-80}:80"      # Frontend
      - "${API_PORT:-8000}:${API_PORT:-8000}"  # Direct API access (optional)
    environment:
      # API Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o}

      # Application Settings
      - DEBUG=${DEBUG:-false}
      - API_TITLE=${API_TITLE:-Code Summarizer API}
      - API_VERSION=${API_VERSION:-1.0.0}

      # Docker specific
      - CONTAINER_MODE=single
      - API_HOST=${API_HOST:-127.0.0.1}
      - API_PORT=${API_PORT:-8000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}

    env_file:
      - .env

    volumes:
      # Optional: Mount for development
      - type: bind
        source: ./logs
        target: /var/log/supervisor
        bind:
          create_host_path: true

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost/health && curl -f http://localhost:$${API_PORT:-8000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - code-summarizer-net

networks:
  code-summarizer-net:
    driver: bridge